export const ROUTING_PERMISSION = {
  //user permissions
  UPDATE_USER: 'UPDATE-USER',
  VIEW_USER: 'VIEW-USER',
  ADD_USER: 'ADD-USER',
  DELETE_USER: 'DELETE-USER',
  LIST_USER: 'LIST-USER',

  //site permissions
  UPDATE_SITE: 'UPDATE-SITE',
  VIEW_SITE: 'VIEW-SITE',
  ADD_SITE: 'ADD-SITE',
  DELETE_SITE: 'DELETE-SITE',
  LIST_SITE: 'LIST-SITE',
};
